name: deploy-guide

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    - guide

# This job installs dependencies, build the guide, and pushes it to `gh-pages`
jobs:
  deploy-guide:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r guide/requirements.txt
        pip install .
        pip install nbstripout
    # Build the guide
    - name: Build the guide
      run: |
        nbstripout guide/*.ipynb
        cd guide && jupyter-book build .
    # Push the book's HTML to gh-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./guide/_build/html
